---
title: Maak een functie in JavaScript
hero_image: images/banner.png
description: Leer hoe je met behulp van JavaScript een functie kunt maken
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: Maak een functie
