---
title: Javascript प्रणाली मध्ये function तयार करा
hero_image: images/banner.png
description: JavaScript प्रणाली मध्ये function कसे तयार करायचे ते शिका
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - title: Function तयार करा
