---
title: Креирај функцију у JavaScript-у
hero_image: images/banner.png
description: Научи како да креираш функцију у JavaScript-у
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: Креирај функцију
