---
title: JavaScript-இல் ஒரு செயற்கூறை உருவாக்கவும்
hero_image: images/banner.png
description: JavaScript-இல் ஒரு செயற்கூறை எவ்வாறு உருவாக்குவது என்று கற்றுக்கொள்ளவும்
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: ஒரு செயற்கூறை உருவாக்கவும்
