---
title: Lag en funksjon i JavaScript
hero_image: images / banner.png
description: Lær hvordan du lager en funksjon i JavaScript
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: Lag en funksjon
