---
title: Tạo một hàm trong JavaScript
hero_image: images / banner.png
description: Tìm hiểu cách tạo hàm bằng JavaScript
original_url:
theme: nguyên mẫu cc
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: Tạo một hàm
