---
title: Crea una funzione in JavaScript
hero_image: images / banner.png
description: Scopri come creare una funzione utilizzando JavaScript
original_url: ""
theme: cc-prototipo
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: Crea una funzione
