---
title: Opret en funktion i JavaScript
hero_image: images / banner.png
description: Lær, hvordan du opretter en funktion ved hjælp af JavaScript
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: Opret en funktion
