---
title: Criar uma função em JavaScript
hero_image: images / banner.png
description: Aprende a criar uma função usando o JavaScript
original_url:
theme: protótipo cc
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: Cria uma função
