---
title: Cria uma função em JavaScript
hero_image: images / banner.png
description: Saiba como criar uma função usando o JavaScript
original_url:
theme: protótipo cc
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: Crie uma função
