---
title: 在 JavaScript 中创建一个函数
hero_image: 图片/ banner.png
description: 学习如何使用 JavaScript 创建函数
original_url: ""
theme: CC-原型
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "JavaScript的"
steps:
  - 
    title: 创建函数
