---
title: Definiraj funkciju u JavaScriptu
hero_image: images/banner.png
description: Saznaj kako definirati funkciju pomoću JavaScript-a
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: Definiraj funkciju
