---
title: Luo funktio JavaScriptissa
hero_image: Kuvien / banner.png
description: Opi luomaan funktio JavaScriptin avulla
original_url:
theme: CC-prototyyppi
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: Luo toiminto
