---
title: Crear una funci贸n en JavaScript
hero_image: images/banner.png
description: Aprende c贸mo crear una funci贸n usando JavaScript
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: Crear una funci贸n
