---
title: Lumikha ng isang function sa JavaScript
hero_image: images/banner.png
description: Alamin kung paano lumikha ng isang function gamit ang JavaScript
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: Lumikha ng isang function
