---
title: Creu swyddogaeth yn JavaScript
hero_image: delweddau / banner.png
description: Dysgwch sut i greu swyddogaeth gan ddefnyddio JavaScript
original_url: ""
theme: cc-prototeip
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: Creu swyddogaeth
