---
title: Creu ffwythiant yn JavaScript
hero_image: images/banner.png
description: Dysgwch sut i greu ffwythiant gan ddefnyddio JavaScript
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: Creu ffwythiant
