---
title: Erstelle eine Funktion in JavaScript
hero_image: images/banner.png
description: Lerne eine Funktion mit JavaScript zu erstellen
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: Eine Funktion erstellen
