---
title: Creează o funcție în JavaScript
hero_image: images/banner.png
description: Învață cum să creezi o funcție folosind JavaScript
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: Creează o funcție
