---
title: Creați o funcție în JavaScript
hero_image: images/banner.png
description: Învățați cum să creați o funcție utilizând JavaScript
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "JavaScript"
steps:
  - title: Creați o funcție
