---
title: Crie uma função em JavaScript
hero_image: images/banner.png
description: Aprenda a criar uma função usando JavaScript
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: Crie uma função
