---
title: جاوا سکرپٹ میں ایک فنکشن بنائیں
hero_image: تصاویر / banner.png
description: جاوا اسکرپٹ کا استعمال کرتے ہوئے ایک فنکشن کیسے بنانا جانیں
original_url:
theme: سی سی پروٹوٹائپ
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "جاوا اسکرپٹ"
steps:
  - 
    title: ایک فنکشن بنائیں
