---
title: Buat fungsi dalam JavaScript
hero_image: gambar / banner.png
description: Pelajari cara membuat fungsi menggunakan JavaScript
original_url: ""
theme: cc-prototipe
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: Buat sebuah fungsi
