---
title: Ustvarite funkcijo v JavaScriptu
hero_image: images/banner.png
description: NauÄite se ustvariti JavaScript funkcijo
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: Ustvarite funkcijo
