---
title: Ustvarite funkcijo v JavaScriptu
hero_image: images / banner.png
description: VeÄ o tem, kako ustvariti funkcijo z uporabo JavaScripta
original_url: ""
theme: cc-prototip
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: Ustvarite funkcijo
