---
title: צור פונקציה ב- JavaScript
hero_image: תמונות / banner.png
description: למד כיצד ליצור פונקציה באמצעות JavaScript
original_url:
theme: אב טיפוס
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "JavaScript"
steps:
  - 
    title: צור פונקציה
