---
title: Hozz létre egy függvényt JavaScriptben
hero_image: images/banner.png
description: Tanuld meg, hogyan lehet létrehozni egy függvényt a JavaScriptben
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: Hozz létre egy függvényt
