---
title: Hozzon létre egy függvényt a JavaScript-ben
hero_image: images / banner.png
description: Ismerje meg, hogyan lehet létrehozni egy függvényt a JavaScript használatával
original_url:
theme: cc-prototípus
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: Hozzon létre egy függvényt
