---
title: 用 JavaScript 創建一個函數
hero_image: 圖片/ banner.png
description: 學習如何使用 JavaScript 創建函式
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: 創建一個函式
