---
title: Utwórz funkcję w JavaScript
hero_image: images/banner.png
description: Dowiedz się, jak utworzyć funkcję za pomocą JavaScript
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: Utwórz funkcję
