---
title: Vytvorte funkciu v jazyku JavaScript
hero_image: images / banner.png
description: Prečítajte si, ako vytvoriť funkciu pomocou jazyka JavaScript
original_url: ""
theme: cc-prototyp
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: Vytvorte funkciu
