---
title: Vytvorenie funkcie v jazyku JavaScript
hero_image: images/banner.png
description: Naučíš sa, ako vytvoriť funkciu v jazyku JavaScript
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: Vytvorenie funkcie
