---
title: Hada abun yi a javascript
hero_image: hotuna/banner
description: Koya yanda ake hada abu indan akayi amfani da Javascript
original_url:
theme: cc-prototype
duration: 0 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: Hada abu
