---
title: Skapa en funktion i JavaScript
hero_image: images/banner.png
description: Lär dig hur du skapar en funktion i JavaScript
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: Skapa en funktion
