---
title: Buat fungsi dalam JavaScript
hero_image: imej / banner.png
description: Ketahui cara membuat fungsi menggunakan JavaScript
original_url:
theme: prototaip cc
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: Buat fungsi
