---
title: Kreiraj funkciju u JavaScript-u
hero_image: images/banner.png
description: Nauči kako da kreiraš funkciju koristeći JavaScript
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - title: Kreiraj funkciju
