---
title: Créer une fonction en JavaScript
hero_image: images/banner.png
description: Apprend à créer une fonction en utilisant JavaScript
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: Créer une fonction
