---
title: Creare una funzione in JavaScript
hero_image: images/banner.png
description: Impara a creare una funzione in JavaScript
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: Creare una funzione
