---
title: Javascript කාර්යයක්(function එකක්) සෑදීම 
hero_image: images / banner.png
description: Learn how to create a function using JavaScript
original_url:
theme: cc-ප්‍රදර්ශකය
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: Create a function
