---
title: Javascript කාර්යයක්(function එකක්) නිර්මාණය කිරීම 
hero_image: images / banner.png
description: JavaScrit මගින් කාර්යයක්(function එකක්) නිර්මාණය කරන්නේ කෙසේදැයි ඉගෙන ගැනීම
original_url:
theme: cc-ප්‍රදර්ශකය
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - 
    title: කාර්යයක්(function එකක්) නිර්මාණය කිරීම
