---
title: JavaScript'te bir fonksiyon oluşturun
hero_image: images/banner.png
description: JavaScript kullanarak bir fonksiyon oluşturmayı öğrenin
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javascript"
steps:
  - title: Bir fonksiyon oluşturun
