---
title: JavaScript'te bir işlev oluştur
hero_image: images / banner.png
description: JavaScript kullanarak bir işlev oluşturmayı öğrenin
original_url: ""
theme: cc-prototip
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "javaScript"
steps:
  - 
    title: Bir işlev oluştur
